name: 'QIIME 2 Library Packaging - Make conda_build_config.yml (build variants)'
description: 'Create a conda_build_config.yml file for use with conda build.'
inputs:
  seed-environment:
    description: 'An environment file produced by `conda env export`'
    required: true
  conda-build-config:
    description: 'The path to place the produced conda_build_config.yml'
    required: true
  conda-activate:
    description: 'An activation script for the conda env to use'
    required: false
    default: ''
  channels:
    description: 'Extra channels to add to the output, useful for adding local channels in addition to what is described by the seed-environment.'
    required: false
    default: '[]'
  skip-first-channel:
    description: 'Drop the first channel in the seed-environment (this is usually a release channel)'
    required: false
    default: false
outputs:
  conda-build-config:
    description: 'The path provided in inputs'
    value: ${{ inputs.conda-build-config }}
  channels:
    description: 'The list of channels defined in the seed-environment'
    value: ${{ steps.make-cbc.outputs.channels }}
  extras:
    description: 'Any information in the "extras" block of the seed-environment'
    value: ${{ steps.make-cbc.outputs.extras }}
runs:
  using: composite
  steps:
    - id: 'setup-path'
      shell: bash
      run: |
        echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH
    - id: 'make-cbc'
      shell: bash
      env:
        PYTHONPATH: "${{ github.action_path }}/../src/"
      run: |
        ${{ inputs.conda-activate }}
        cat <<EOF | make-cbc.py
        ${{ toJSON(inputs) }}
        EOF
