{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-nothing-to-see-here
  version: {{ version }}

source:
  path: .

build:
  script: python setup.py install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2

test:
  requires:
    - pytest
  imports:
    - qiime2.plugins.nothing_to_see_here
