name: 'QIIME 2 Library Packaging'
description: 'Build, test, and distribute a QIIME 2 conda package'
inputs:
  recipe-path:
    description: 'Path to recipe'
    required: false
    default: 'ci/recipe'
  package-name:
    description: 'Name of QIIME 2 package'
    required: true
  build-target:
    description: 'Target QIIME 2 release cycle: "tested" or "staged" or "released"'
    required: true
    default: 'release'
  additional-tests:
    description: 'Additional tests to run post-build'
    required: false
  library-token:
    description: 'A package token from library.qiime2.org. Required to upload built packages.'
    required: true
    default: ''
runs:
  using: "composite"
  # TODO: is this supported?
  env:
    BUILD_DIR: ${{ github.workspace }}/built-package
    # TODO: can we just look up the INPUTS_* directly?
    RECIPE_PATH: ${{ inputs.recipe-path }}
    PACKAGE_NAME: ${{ inputs.package-name }}
    BUILD_TARGET: ${{ inputs.build-target }}
    ADDITIONAL_TESTS: ${{ inputs.additional-tests }}
    LIBRARY_TOKEN: ${{ inputs.library-token }}
  steps:
    - id: setup
      run: ${{ github.action_path }}/bin/setup.sh
      shell: bash
    - id: build
      run: ${{ github.action_path }}/bin/build.sh
      shell: bash
    - id: artifact-caching
      # run: const artifactClient = artifact.create()
          #  const uploadResult = await artifactClient.uploadArtifact(arch[1], files, buildDir)
      shell: bash
    - id: testing
      run: ${{ github.action_path }}/bin/testing.sh
      shell: bash
    - id: lib-token
      run: ${{ github.action_path }}/bin/lib-token.sh
      shell: bash
