name: 'QIIME 2 Library Packaging'
description: 'Build, test, and distribute a QIIME 2 conda package'
inputs:
  recipe-path:
    description: 'Path to recipe'
    required: false
    default: 'ci/recipe'
  package-name:
    description: 'Name of QIIME 2 package'
    required: true
  release-target:
    description: 'Target QIIME 2 release cycle: "dev" or "release"'
    required: true
    default: 'release'
  distro-target:
    description: 'Target QIIME 2 distribution'
    required: true
  additional-tests:
    description: 'Additional tests to run during package building'
    required: false
  library-token:
    description: 'A package token from library.qiime2.org. Required to upload built packages.'
    required: true
    default: ''
runs:
  using: composite
  steps:
    - id: 'setup-conda'
    - shell: bash
    - run: |
        sudo conda install \
        -n base \
        -q \
        -y \
        -c conda-forge \
        -c defaults \
        --override-channels \
        --update-all \
        conda \
        boa \
        conda-build \
        conda-verify
    - id: 'build-package'
      uses: 'qiime2/action-library-packaging/build-package@beta'
      with:
        recipe-path: ${{ inputs.recipe-path }}
        conda-build-config: ${{ steps.config.outputs.conda-build-config }}
        channels: ${{ steps.config.outputs.channels }}
        output-channel: ${{ steps.config.outputs.output-channel }}
    - id: 'make-prefix'
      shell: bash
      run: 'mkdir ./test_env'
    - id: 'install-package'
      uses: 'qiime2/action-library-packaging/install-package@beta'
      with:
        channels: ${{ steps.config.outputs.channels }}
        package-name: ${{ steps.build.outputs.package-name }}
        package-version: ${{ steps.build.outputs.package-version }}
        conda-prefix: './test_env'
    - id: 'test-package'
      uses: 'qiime2/action-library-packaging/test-package@beta'
      with:
        conda-prefix: ${{ steps.install-package.outputs.conda-prefix }}
        package-filepath: ${{ steps.install-package.outputs.conda-prefix }}/${{ steps.build-package.outputs.conda-subdir }}/${{ steps.build-package.outputs.package-filename }}
        additional-tests: ${{ inputs.additional-tests }}
