name: 'QIIME 2 Library Packaging'
description: 'Build, test, and distribute a QIIME 2 conda package'
inputs:
  recipe-path:
    description: 'Path to recipe'
    required: false
    default: 'ci/recipe'
  package-name:
    description: 'Name of QIIME 2 package'
    required: true
  build-target:
    description: 'Target QIIME 2 release cycle: "tested" or "staged" or "released"'
    required: true
    default: 'release'
  additional-tests:
    description: 'Additional tests to run post-build'
    required: false
  library-token:
    description: 'A package token from library.qiime2.org. Required to upload built packages.'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - id: recipe-path
      run: ${{ github.action_path }}/recipe.sh
      shell: bash
    - id: package-name
      run: ${{ github.action_path }}/package.sh
      shell: bash
    - id: build-target
      run: ${{ github.action_path }}/build.sh
      shell: bash
    - id: additional-tests
      run: ${{ github.action_path }}/testing.sh
      shell: bash
    - id: library-token
      run: ${{ github.action_path }}/library.sh
      shell: bash
