name: 'QIIME 2 Library Packaging'
description: 'Build, test, and distribute a QIIME 2 conda package'
inputs:
  recipe-path:
    description: 'Path to recipe'
    required: false
    default: 'ci/recipe'
  package-name:
    description: 'Name of QIIME 2 package'
    required: true
  build-target:
    description: 'Target QIIME 2 release cycle: "tested" or "staged" or "released"'
    required: true
    default: 'released'
  additional-tests:
    description: 'Additional tests to run post-build'
    required: false
  library-token:
    description: 'A package token from library.qiime2.org. Required to upload built packages.'
    required: true
    default: ''
runs:
  using: 'composite'
  # env:
  #   BUILD_DIR: ${{ github.workspace }}/built-package
  #   RUNNER_OS: ${{ runner.os }}
  #   RECIPE_PATH: ${{ inputs.recipe-path }}
  #   PACKAGE_NAME: ${{ inputs.package-name }}
  #   BUILD_TARGET: ${{ inputs.build-target }}
  #   ADDITIONAL_TESTS: ${{ inputs.additional-tests }}
  #   LIBRARY_TOKEN: ${{ inputs.library-token }}
  steps:
    - env:
        BUILD_DIR: ${{ github.workspace }}/built-package
        RUNNER_OS: ${{ runner.os }}
      run: ${{ github.action_path }}/bin/setup.sh
      shell: bash
    - run: ${{ github.action_path }}/bin/build.sh
      shell: bash
    # TODO: figure this out...
    # - run: ${{ github.action_path }}/bin/upload_artifact.sh
    #   shell: bash
    # - run: ${{ github.action_path }}/bin/testing.sh
    #   shell: bash
    # - run: ${{ github.action_path }}/bin/lib-token.sh
    #   shell: bash
