name: 'Mirror channel'
inputs:
  packages:
    required: true
  remote_channel:
    required: true
  local_channel:
    required: true

runs:
  using: composite
  steps:
    - id: 'setup-path'
      shell: bash
      run: |
        echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH
    - id: 'make-cbc'
      shell: bash
      env:
        PYTHONPATH: "${{ github.action_path }}/../src/"
      run: |
        cat <<EOF | mirror.py
        ${{ toJSON(inputs) }}
        EOF
