name: 'QIIME 2 Library Packaging - Setup Environment'
description: 'Install and configure conda-build and libmamba'

inputs:
  conda-prefix:
    description: 'The conda prefix environment to set up'
    required: false
    default: ${{ github.workspace }}/alp-base-env/
  cache-name:
    description: 'The name of the cache to store the environment in'
    required: false
    default: 'alp-base-env'
  skip-cache:
    description: 'Do not use a cache'
    required: false
    default: false

outputs:
  conda-prefix:
    description: 'The conda prefix environment which has been set up'
    value: ${{ inputs.conda-prefix }}
  conda-activate:
    description: 'Activates this environment via sourcing (e.g. `. foo`)'
    value: ${{ steps.create-env.outputs.conda-activate }}

runs:
  using: composite
  steps:

    - id: 'create-env'
      name: 'Create base environment for ALP'
      uses: qiime2/action-library-packaging/create-env@beta
      with:
        conda-prefix: ${{ inputs.conda-prefix }}
        environment-file: ${{ github.action_path }}/conda-environment.yml
        cache-name: ${{ inputs.cache-name }}
        skip-cache: ${{ inputs.skip-cache }}
