name: 'Private utility - make a temporary directory with some prefix'
description: 'Makes a temporary directory with a given name as a prefix'
inputs:
  prefix:
    description: 'Prefix to use in the random name'
    required: false
    default: 'tmp'
outputs:
  path:
    description: 'A randomly generated directory'
    value: ${{ steps.mktemp.outputs.path }}
runs:
  using: composite
  steps:
    - id: 'mktemp'
      shell: bash
      env:
        TMPDIR: ${{ runner.temp }}
      run: echo path=$(mktemp -d ${{ inputs.prefix }}-XXXXXXX) >> $GITHUB_OUTPUT
