name: 'QIIME 2 Library Packaging - Build'
description: 'Build a conda package'
inputs:
  conda-activate:
    description: 'An activation script for the conda env to use'
    required: false
  recipe-path:
    description: 'Path to package recipe'
    required: true
  conda-build-config:
    description: 'conda_build_config.yml to use while building'
    required: true
  channels:
    description: 'A list of channels needed to build the package'
    required: true
  output-channel:
    description: 'Local (file-system) channel to place the built package'
    required: true
  dry-run:
    description: 'Produce action outputs without building'
    required: false
    default: false
outputs:
  package-name:
    description: 'Name of built package'
    value: ${{ steps.build-package.outputs.name }}
  package-version:
    description: 'Version of built package'
    value: ${{ steps.build-package.outputs.version }}
  package-filename:
    description: 'Filename of built package'
    value: ${{ steps.build-package.outputs.filename }}
  package-build:
    description: 'Build ID of built package'
    value: ${{ steps.build-package.outputs.build }}
  conda-subdir:
    description: 'Conda channel subdirectory'
    value: ${{ steps.build-package.outputs.subdir }}
runs:
  using: composite
  steps:
    - id: 'setup-path'
      shell: bash
      run: echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH
    - id: 'build-package'
      shell: bash
      env:
        PYTHONPATH: "${{ github.action_path }}/../src/"
      run: |
        [ -n "${{ inputs.conda-activate }}" ] && ${{ inputs.conda-activate }}
        cat <<EOF | build-package.py
        ${{ toJSON(inputs) }}
        EOF
