name: 'rachis Library Packaging - Setup Plugin Environment File'
description: 'Setup or update the environment file for a rachis plugin'
inputs:
  environment-fp:
    description: 'Path to the environment file'
    required: true
  pip-spec:
    description: 'Pip command to use'
    required: true
  epoch:
    description: 'Target rachis epoch'
    required: true
  distro:
    description: 'Target rachis distribution'
    required: true

runs:
  using: composite
  steps:
  - id: 'setup-environment-file'
    shell: bash
    run: |
      echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH
  - id: 'setup-plugin-env-file'
    shell: bash
    env:
      PYTHONPATH: "${{ github.action_path }}/../src/"
    run: |
      cat <<EOF | setup-plugin-env-file.py
      ${{ toJSON(inputs) }}
      EOF
