name: 'QIIME 2 Library Packaging - Test'
description: 'Test a conda package'

inputs:
  conda-activate:
    description: 'An activation script for the conda env to use'
    required: true
  package-path:
    description: 'The path to the .tar.bz2 to test'
    required: true
  channels:
    required: false
    description: "Channels to search for additional packages in"
    default: '["conda-forge", "bioconda"]'

runs:
  using: composite
  steps:
  - id: 'setup-path'
    shell: bash
    run: echo "$GITHUB_ACTION_PATH/bin/" >> $GITHUB_PATH

  - name: install browsers & set tmpdirs for Selenium tests
    shell: bash
    run: |
      dnf -y install epel-release
      dnf -y install chromium firefox

      echo "HOME=$PWD/.home" >> $GITHUB_ENV
      echo "XDG_CACHE_HOME=$PWD/.cache" >> $GITHUB_ENV
      echo "XDG_CACHE_HOME=$PWD/.config" >> $GITHUB_ENV
      echo "TMPDIR=$PWD/.tmp" >> $GITHUB_ENV
      mkdir -p .home .cache .config .tmp

  - id: 'test-package'
    shell: bash
    env:
      PYTHONPATH: "$GITHUB_ACTION_PATH/../src/"
    run: |
      ${{ inputs.conda-activate }}
      export PYTHONPATH="$GITHUB_ACTION_PATH/../src${PYTHONPATH:+:$PYTHONPATH}"
      cat <<EOF | python "$GITHUB_ACTION_PATH/bin/test-package.py"
      ${{ toJSON(inputs) }}
      EOF

  - id: 'test-package2-electric-boogaloo'
    shell: bash
    env:
      PYTHONPATH: "$GITHUB_ACTION_PATH/../src/"
    run: |
      ${{ inputs.conda-activate }}
      export PYTHONPATH="$GITHUB_ACTION_PATH/../src${PYTHONPATH:+:$PYTHONPATH}"
      cat <<EOF | python "$GITHUB_ACTION_PATH/bin/test-package2-electric-boogaloo.py"
      ${{ toJSON(inputs) }}
      EOF
