name: 'QIIME 2 Library Packaging - Build Distro Metapackage'
description: 'Build a QIIME 2 metapackage'
inputs:
  conda-activate:
    description: 'An activation script for the conda env to use'
    required: false
    default: ''
  metapackage-name:
    description: 'Name for the built distribution (e.g. qiime2-core)'
    required: true
  metapackage-version:
    description: 'Version for the built distribution'
    required: true
  seed-environment:
    description: 'An environment file produced by `conda env export`'
    required: true
  channels:
    description: 'Extra channels to use.'
    required: false
    default: '[]'
  output-channel:
    description: 'Local (file-system) channel to place the built package'
    required: true
outputs:
  package-name:
    description: 'Name of built package'
    value: ${{ steps.build-metapackage.outputs.package-name }}
  package-version:
    description: 'Version of built package'
    value: ${{ steps.build-metapackage.outputs.package-version }}
  package-filename:
    description: 'Filename of built package'
    value: ${{ steps.build-metapackage.outputs.package-filename }}
  conda-subdir:
    description: 'Conda channel subdir'
    value: ${{ steps.build-metapackage.outputs.conda-subdir }}
runs:
  using: composite
  steps:
    - id: 'setup-path'
      shell: bash
      run: echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH
    - id: 'make-recipe-dir'
      uses: 'qiime2/action-library-packaging/_mktmpdir@beta'
    - id: 'make-cbc'
      uses: 'qiime2/action-library-packaging/make-conda-config@beta'
      with:
        seed-envrionment: ${{ inputs.seed-environment }}
        channels: ${{ inputs.channels }}
        conda-build-config: '${{ steps.make-recipe-dir.outputs.path }}/conda_build_config.yml'
    - id: 'template-metapackage'
      shell: bash
      env:
        PYTHONPATH: "${{ github.action_path }}/../src/"
      run: |
        cat <<EOF | template-metapackage.py ${{ steps.make-recipe-dir.outputs.path }}
        ${{ toJSON(inputs) }}
        EOF
    - id: 'build-metapackage'
      uses: 'qiime2/action-library-packaging/build-package@beta'
      with:
        conda-activate: ${{ inputs.conda-activate }}
        recipe-path: ${{ steps.template-metapackage.outputs.recipe-path }}
        conda-build-config: ${{ steps.make-cbc.outputs.conda-build-config }}
        channels: ${{ steps.make-cbc.outputs.channels }}
        output-channel: ${{ inputs.output-channel }}
