name: 'QIIME 2 Library Packaging - Install'
description: 'Install a conda package'
inputs:
  conda-activate:
    description: 'An activation script for the conda env to use'
    required: false
    default: ''
  channels:
    description: 'A list of channels needed to build the package'
    required: true
  package-name:
    description: 'The name of a conda package to install'
    required: true
  package-version:
    description: 'The version of a conda package to install'
    required: true
  conda-prefix:
    description: 'Path to the prefix to be populated with a conda environment'
    required: true
outputs:
  conda-prefix:
    description: 'Same path provided to input'
    value: ${{ inputs.conda-prefix }}
runs:
  using: composite
  steps:
  - id: 'setup-path'
    shell: bash
    run: |
      echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH
  - id: 'install-package'
    shell: bash
    env:
      PYTHONPATH: "${{ github.action_path }}/../src/"
    run: |
      ${{ inputs.conda-activate }}
      cat <<EOF | install_package.py
      ${{ toJSON(inputs) }}
      EOF
