name: 'rachis Library Packaging - Configure Distro Matrix'
description: ''
inputs:
  package-name:
    description: 'Name of rachis package'
    required: true
  release-target:
    description: 'Target rachis release cycle: "dev" or "release"'
    required: true
    default: 'release'
